version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
  pre_build:
    commands:
      - echo "Entering the pre_build phase..."
      - echo "We will list the files in the directory."
      - ls -la
  build:
    commands:
      - echo "Entering the build phase..."
      - echo "Build started on `date`"
  post_build:
    commands:
      - echo "Entering the post_build phase..."
      - echo "Build completed."