# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devsecops-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devsecops-app
  template:
    metadata:
      labels:
        app: devsecops-app
    spec:
      containers:
      - name: my-flask-app
        # IMPORTANT: This placeholder now points to Docker Hub.
        # It will be replaced by the GitHub Actions workflow.
        image: prerna307/devsecops-app:latest
        ports:
        - containerPort: 5000
        env:
          - name: MY_SECRET_PASSWORD
            valueFrom:
              secretKeyRef:
                name: my-app-secret
                key: MY_SECRET_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: devsecops-app-service
spec:
  selector:
    app: devsecops-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer