name: DevSecOps CI/CD to Kubernetes with Docker Hub

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  DOCKER_REPO: devsecops-app
  EKS_CLUSTER_NAME: ${{ secrets.EKS_CLUSTER_NAME }}

jobs:
  # Job 1: Scan Terraform code
  tfsec-scan:
    name: Terraform Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1.0.2
        with:
          working_directory: infra
          soft_fail: true

  # Job 2: Build, Scan, and Push using OFFICIAL DOCKER ACTIONS
  build-and-push-image:
    name: Build, Scan & Push Docker Image
    runs-on: ubuntu-latest
    needs: tfsec-scan
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    outputs:
      image_with_tag: ${{ steps.build-and-push.outputs.image_with_tag }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # --- THIS IS THE CRITICAL FIX ---
      # This step uses an official action to generate metadata like tags.
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_REPO }}
          tags: |
            type=sha,prefix=,format=short

      # This is the new, official, robust build-and-push action.
      # It handles outputs correctly.
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Set Image Output
        id: set-image-output
        run: echo "image_with_tag=${{ steps.meta.outputs.tags }}" >> $GITHUB_OUTPUT

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ steps.meta.outputs.tags }}
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL'

  # Job 3: Deploy to EKS
  deploy-to-eks:
    name: Deploy to EKS
    runs-on: ubuntu-latest
    needs: build-and-push-image
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Configure kubectl for EKS
        run: aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER_NAME }} --region ${{ env.AWS_REGION }}

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/sealed-secret.yaml
          
          # This will now receive the correct output from the build job.
          export IMAGE_URI="${{ needs.build-and-push-image.outputs.image_with_tag }}"
          
          # The sed command will now work.
          sed -i "s|prerna307/devsecops-app:latest|$IMAGE_URI|" k8s/deployment.yaml
          
          kubectl apply -f k8s/deployment.yaml